server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:/code_folder/portfolio/jpashop
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create # create, none. none으로 바꾸면 table 드랍하지 않음(data base에 넣어놓은 data 그대로 쓸 수 있음)
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace